version: '3'
services:
  client:
    build: client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8080:8080"
  server:
    build: server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run develop
